[package]
name = "RuSTm"
version = "0.1.0"
authors = ["Dzyunka <mast-94@mail.ru>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
